name: tombala
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: 
    sdk: flutter
  intl: ^0.17.0 


# Firebase
  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.4
  firebase_core_web: ^1.5.3
  cloud_firestore: ^3.1.5



# State Managment
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2
  mobx_codegen: ^2.0.2
  json_annotation: ^4.1.0
  get_it: ^7.2.0

# Design
  flex_color_scheme: ^4.2.0
  loading_overlay: ^0.3.0
  google_fonts: ^2.2.0
  rename: ^2.0.1
  flutter_native_splash: ^2.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  json_serializable: ^4.1.4
  lint: ^1.8.2
  flutter_launcher_icons: ^0.9.2





flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#023047"
  image: assets/splash/splash.png
  backgroundColor: "#023047"
  branding: assets/splash/splash.png
  branding_mode: bottom
  android_gravity: center
  fullscreen: true
