name: tombala
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: 
    sdk: flutter
  intl: ^0.17.0 


# Firebase
  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.4
  firebase_core_web: ^1.5.3
  cloud_firestore: ^3.1.5



# State Managment
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2
  mobx_codegen: ^2.0.2
  json_annotation: ^4.1.0
  get_it: ^7.2.0

# Design
  flex_color_scheme: ^4.2.0
  loading_overlay: ^0.3.0
  google_fonts: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  json_serializable: ^4.1.4
  lint: ^1.8.2


flutter:
  generate: true
  uses-material-design: true
